//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cd_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int productId { get; set; }
        public string productName { get; set; }
        public decimal price { get; set; }
    }
}
