//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cd_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int productId { get; set; }
        public string productName { get; set; }
        public int publisherId { get; set; }
        public int genreId { get; set; }
        public int categoryId { get; set; }
        public decimal price { get; set; }
        public Nullable<int> count { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
